### ISSUE TITLE
cannot import name 'TMDB' from 'tmdb'

### ISSUE THREAD

**Issue by b1n4ryj4n** [Merenon/django-tmdb#2]
hey i recently installed your lib via pip install django-tmdb and tried to add your wrapper in my app but it says always cannot import name 'TMDB' from 'tmdb' if i follow your install steps.

`cannot import name 'TMDB' from 'tmdb' (c:\Users\Jan\Desktop\django\venv\lib\site-packages\tmdb\__init__.py)`

it seams that pypi needs a version update because if i clone this repo and install it without pip it works.

**Comment by Merenon** [comment]
Hey,
you're right, please see PR #1.
As I'm not actively maintaining this package anymore, the new release hasn't made it to the pip repository.

You can either use:
```python
from tmdb.tmdb import TMDB
tmdb = TMDB()
```

and/or add the following to `__init__.py`
```python
from .tmdb import TMDB
```

**Comment by Merenon** [comment]
Hi @b1n4ryj4n,
I have yet to decided to create a new version on pypi.
Please try the new version via `pip install django-tmdb==0.2`
