### ISSUE TITLE
'Settings' object has no attribute 'TMDB_BASE_URL'

### ISSUE THREAD

**Issue by GHEEWALAKARTIK** [Merenon/django-tmdb#3]
I am trying to use TMDB_BASE_URL in setting.py file then this error occur.

**Comment by Merenon** [comment]
Have you successfully followed step 3) of the guide and added `TMDB_API_KEY = 'yourtmdbapikey'` to your `settings.py`?

Which version of Django and django-tmdb are you using?

**Comment by GHEEWALAKARTIK** [comment]
Yes, I have follow the same step as you mention.
and I am using Django==3.1, django-tmdb==0.2

**Comment by Merenon** [comment]
Maybe the way Django handles setting properties has changed with Django 3.1.

How are you importing the settings? Via `from django.conf import settings`?

How are you accessing the property? via `settings. TMDB_API_KEY`?

Can you maybe add some extracts of the relevant files to aid in debugging the issue?

**Comment by GHEEWALAKARTIK** [comment]
1. Install django-tmdb library.
2. Add TMDB_API_KEY = 'MyKey' in setting.py file.
that's it.

**Comment by Merenon** [comment]
It's setting**s**.py. Are you using any nested setting configuration?
Any additional debugging output? A stacktrace?

**Comment by GHEEWALAKARTIK** [comment]
And you see which error I get: 'Settings' object has no attribute **TMDB_BASE_URL** 
TMDB_BASE_URL = ???

**Comment by Merenon** [comment]
Sorry, you're right, totally misread it.

Please try to add `TMDB_BASE_URL  = 'https://api.themoviedb.org/3/'` to your settings file. Strange, that it's not part of the  README anymore...
